---
version: "2"
services:
  pcd:
    container_name: gripmock
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4770:4770
      - 4771:4771
    volumes:
      - F:\Github_Project\gripmock\grpc-protos:/proto
    command:
      [
        "--stub=/proto/grpcStubs",
        "/proto/bnd_service_productdata_enums.proto",
        "/proto/bnd_service_productdata_generic_bank_product.proto",
      ]

volumes:
  grpc-protos:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: grpc-protos
